controllers/AnyTestsController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\RequestVue;
use app\models\UploadForm;
use yii\web\UploadedFile;

class AnyTestsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        
        return $this->render('index');
    }
    /**
     * UserForm action.
     *
     * @return string
     */
    public function actionUserForm()
    {
       
        $this->view->registerCssFile('https://use.fontawesome.com/releases/v5.5.0/css/all.css');
        $this->view->registerCssFile('@web/css/userForm.css');
        return $this->render('userForm');
    }

    public function actionVueOpportunities()
    {
        return $this->render('vueOpportunities');
    }
    

    public function actionVuerequest()
    {
        if(Yii::$app->request->isAjax){
            $name = Yii::$app->request->post('name');
            $thing = Yii::$app->request->post('thing');
            $total = (int) Yii::$app->request->post('total');
            $model = new RequestVue();
            $model->name = $name;
            $model->thing = $thing;
            $model->total = $total;
            $model->save();
        }
        $sendModel = RequestVue::find()->orderBy('id desc')->limit(10)->asArray()->all();
        return json_encode($sendModel);
    }
    
    public function actionVuerequestanswer()
    {
        
        $sendModel = RequestVue::find()->orderBy('id desc')->limit(10)->asArray()->all();
        
        
        return json_encode($sendModel);
        
    }

    /**
     * Login action.
     *
     * @return Response|string
     */

    public function actionUpload()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {
            $model->imageFiles = UploadedFile::getInstances($model, 'imageFiles');
            if ($model->upload()) {
                // file is uploaded successfully
               // return $this->render('viewLinkToPdf', ['model' => $model]);
                return $this->actionTestPdf();
            }
        }

        $this->view->registerCssFile('@web/css/uploadForm.css');

        return $this->render('viewForFiles', ['model' => $model]);
    }

    public function actionTestPdf()
    {
        $content = $this->renderPartial('yulMaket');

        /*echo '<pre>';
        var_dump($someValue->makePdf($content));
        echo '</pre>';
        exit;*/
        $pdf = Yii::$app->pdf;
        $pdf->content = $content;
        $pdf->cssInline = '.forTitle{text-align:center} .forContent{margin-left: 20px;}';
        $pdf->filename = 'uploads/yurMaket/111.pdf';
        $pdf->destination = \kartik\mpdf\Pdf::DEST_FILE;
        //$pdf->output->dest = 'uploads';
        $pdf->render();

        $model = new UploadForm();
        $this->view->registerCssFile('@web/css/uploadForm.css');
        return $this->render('viewForFiles', ['model' => $model]);
        //return $this->render('testPdf');
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    public function actionList()
    {
        $data = "ttt";
        if(Yii::$app->request->isAjax){
            $id = (int)Yii::$app->request->post('id');
            $data = $id;
            $myProducts = "<option value='0'>" . "Выбрать" . "</option>";
            //$this->option = "<option value='0'>" . AirlinesModule::t('module', 'AIRLINES_PROMPT_FORM') . "</option>";
            /*$products = \app\models\Product::find()
                ->Where('referenceId=:id',[':id' => $id])
                ->orderBy('referenceId')
                ->all();
            foreach ($products as $product){
                $myProducts .= '<option value="' . $product->id . '">' . $product->title . '</option>';
            }selected='selected'*/
            $myProducts .="<option value='cart'>"."Cart"."</option>".
                "<option data-divider='true' disabled>"."____"."</option>".
                "<option value='openmodaloption'>"."Create new list"."</option>";
            $data = $myProducts;
        }
        //return $this->option;
        return $data;
    }

    /**
     * TreeTemplate action.
     *
     * @return string
     */

    public function actionTreeTemplate()
    {

        /*$this->view->registerCssFile('@web/treeTemplate/css/font-awesome.min.css');
        $this->view->registerCssFile('@web/treeTemplate/css/main.css');
        $this->view->registerCssFile('@web/treeTemplate/css/responsive.css');

        $this->view->registerJsFile('@web/treeTemplate/js/jquery.cookie.js', ['position'=>yii\web\View::POS_LOAD]);
        $this->view->registerJsFile('@web/treeTemplate/js/jquery.accordion.js', ['position'=>yii\web\View::POS_LOAD]);
        $this->view->registerJsFile('@web/treeTemplate/js/main.js', ['position'=>yii\web\View::POS_LOAD]);*/

        $this->layout = 'mainTree';
        return $this->render('treeTemplate');
    }

        
    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');
            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/MakePdfController.php
<?php

namespace app\controllers;

use kartik\mpdf\Pdf;

class MakePdfController extends \yii\web\Controller
{
    public function actionIndex()
    {
         $content = $this->renderPartial('maket');
    
    // setup kartik\mpdf\Pdf component
    $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_CORE, 
        // A4 paper format
        'format' => Pdf::FORMAT_A4, 
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT, 
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER, 
        // your html content input
        'content' => $content,  
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting 
        'cssFile' => '@vendor/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}', 
         // set mPDF properties on the fly
        'options' => ['title' => 'Documents'],
         // call mPDF methods on the fly
        'methods' => [ 
            'SetHeader'=>['Documents'],
            'SetFooter'=>['{PAGENO}'],
        ]
    ]);
    
    // return the pdf output as per the destination setting
    return $pdf->render(); 
    }

}

controllers/TreeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\TreeTemplate;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TreeController implements the CRUD actions for TreeTemplate model.
 */
class TreeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Show opportunities
     * @return mixed
    */

    public function actionOpportunities()
    {
        $model = new TreeTemplate();

        return $this->render('opportunities', [
            'model' => $model,
        ]);
    }

    /**
     * Lists all TreeTemplate models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => TreeTemplate::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TreeTemplate model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TreeTemplate model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TreeTemplate();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TreeTemplate model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TreeTemplate model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the TreeTemplate model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TreeTemplate the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TreeTemplate::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
             ['label' => 'PHP', 'items' => [            
                ['label' => 'CsvToArray', 'url' => ['/site/index']],// /any-tests/index
                //['label' => 'MakePdf', 'url' => ['/make-pdf/index']],
                ['label' => 'Upload', 'url' => ['/any-tests/upload']],
                ['label' => 'TreeTemplate', 'url' => ['/any-tests/tree-template']],
                //['label' => 'TestPdf', 'url' => ['/any-tests/test-pdf']],
            ]],
            ['label' => 'Js', 'items' => [
                ['label' => 'UsersForm', 'url' => ['/any-tests/user-form']],
                ['label' => 'VueJs', 'url' => ['/any-tests/vue-opportunities']],
            ]],
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/mainTree.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\assets\TreeAsset;

TreeAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home</title>
          
    <link rel="shortcut icon" href="<?= Url::to('@web/favicon.ico'); ?>" type="image/x-icon">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
    <?php $this->head() ?>
</head><!--/head-->
<body>
<?php $this->beginBody() ?>
    <header id="header"><!--header-->

        

    
        <div class="header-bottom"><!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">

                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="<?= Url::to(['site/index']); ?>" class="active">Home</a></li>
                                <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="#">Products</a></li>
                                        <li><a href="#">Product Details</a></li> 
                                        <li><a href="#">Checkout</a></li> 
                                        <li><a href="#">Cart</a></li> 
                                        <li><a href="#">Login</a></li> 
                                    </ul>
                                </li> 
                                <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="#">Blog List</a></li>
                                        <li><a href="#">Blog Single</a></li>
                                    </ul>
                                </li> 
                                <li><a href="<?= Url::to(['tree/opportunities']) ?>">Settings</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="search_box pull-right">
                            <form method="get" action="<?= Url::to(['category/search']) ?>">
                                <input type="text" placeholder="Search" name="q">
                            </form> 
                        </div>
                    </div>
                </div>
            </div>
        </div><!--/header-bottom-->
    </header><!--/header-->

    
   <?= $content ?>


        
 <footer id="footer"><!--Footer-->

        
    </footer><!--/Footer-->

<?php
\yii\bootstrap\Modal::begin([
'header'=>'<h2>Корзина</h2>',
'id' => 'cart',
'size' => 'modal-lg',
'footer'=>' <button type="button" class="btn btn-default" data-dismiss="modal">Продолжить покупки</button>
        <a href="' . Url::to(['cart/view']) . '" class="btn btn-success" >Оформить заказ</a>
        <button type="button" class="btn btn-danger" onclick="clearCart()">Очистить корзину</button>',
]);

\yii\bootstrap\Modal::end();
?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>